### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by S-zebra** [izszzz/tunescore#342]
https://tunescore.dev/ is not working.

# Error
```
Error: Page not found
The requested URL was not found on this server.
```

**Comment by izszzz** [comment]
レポートありがとうございます。

以下の理由で一時的に外部アクセスを遮断しています。

## alphaTabの再検討
機能拡張を行いたいが、alphaTabの発展が遅い。
代わりのOSSを採用するか楽譜表示システムの構築するか検討しているので、Webの状態を確認する必要がない。

## Prismaの再検討
prisma-generatorで生成される型ファイルが非常に多く、エディタでの型読み込みが遅い。
devcontianerなどの問題もあるはずですが、Vscodeでこのプロダクトのdevcontainerを開くと型の読み込みに1分以上かかることが多いです。

## 本番環境を確認する頻度が減った
現在は別プロダクトに力を入れています。

なにかありましたら、気軽にご連絡ください！
